version: '3.8'

services:
  jenkins:
    build:
      context: .
      dockerfile: Jenkins.Dockerfile
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - /workspaces/ensf400-project-group48/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
